#!/bin/sh

BROOT="build/bundled"
BPROJ="${BROOT}"

DPROJ="ext/remotig/node-ws/public"

polymer build

echo "Deploying to $DPROJ"
[ -d "$DPROJ/src" ] || mkdir "$DPROJ/src"
[ -d "$DPROJ/bower_components" ] || mkdir "$DPROJ/bower_components"
cp "${BPROJ}/src/smartceiver-app.html" "${DPROJ}/src/"
cp "${BPROJ}/index.html" "${DPROJ}/"
cp "${BPROJ}/manifest.json" "${DPROJ}/"
cp "${BROOT}/bower.json" "${DPROJ}/"
cp "${BROOT}/service-worker.js" "${DPROJ}/"
cp -r "${BPROJ}/images" "${DPROJ}/"
cp -r "${BROOT}/bower_components/webcomponentsjs" "${DPROJ}/bower_components/"
